'use strict'

/**
 * ============================================================
 *  FACELESS ANIMAL STUDIOS — STATIC DEV SERVER
 *  server.js
 *
 *  Pure Node.js — zero npm dependencies.
 *  Serves all static files from the project root.
 *
 *  On startup:
 *    1. Reads SUPABASE_URL and SUPABASE_ANON_KEY from env vars
 *    2. Writes assets/js/env.js so the browser can access them
 *    3. Starts HTTP server on process.env.PORT (default: 3000)
 *
 *  For production (Cloudflare Pages):
 *    Run `node scripts/generate-env.js` as the build command.
 *    That script does step 1–2 without starting the server.
 *    Set SUPABASE_URL, SUPABASE_ANON_KEY, and SUPABASE_SERVICE_ROLE_KEY
 *    in the CF Pages dashboard.
 *
 *  Usage:
 *    SUPABASE_URL=https://xxx.supabase.co \
 *    SUPABASE_ANON_KEY=eyJh... \
 *    SUPABASE_SERVICE_ROLE_KEY=eyJh... \
 *    node server.js
 *
 *  API endpoints (server-side, not served as static files):
 *    POST /api/dm/upload  — Authenticated DM file upload proxy.
 *                           Requires SUPABASE_SERVICE_ROLE_KEY.
 *                           See handleDMUpload() below.
 * ============================================================
 */

const http  = require('http')
const https = require('https')
const fs    = require('fs')
const path  = require('path')

const PORT = parseInt(process.env.PORT || '3000', 10)
const ROOT = __dirname


// ── STEP 1: WRITE env.js FROM ENVIRONMENT VARIABLES ─────────────────
// This file is loaded by the browser before any Supabase-aware modules.
// It sets window.__FAS_CONFIG so supabase-client.js can read credentials
// without hardcoding them into source code.
writeEnvConfig()

function writeEnvConfig() {
  const url  = process.env.SUPABASE_URL      || ''
  const key  = process.env.SUPABASE_ANON_KEY || ''
  const ready = Boolean(url && key)

  const content = [
    '/* AUTO-GENERATED by server.js — do not edit manually.',
    '   Set SUPABASE_URL and SUPABASE_ANON_KEY env vars and restart the server.',
    '   This file is gitignored. The server regenerates it on every startup. */',
    '',
    'window.__FAS_CONFIG = {',
    `  supabaseUrl:     ${JSON.stringify(url)},`,
    `  supabaseAnonKey: ${JSON.stringify(key)},`,
    `  ready:           ${JSON.stringify(ready)},`,
    '}',
  ].join('\n')

  try {
    fs.writeFileSync(path.join(ROOT, 'assets', 'js', 'env.js'), content, 'utf8')
  } catch (e) {
    console.warn('[FAS] Could not write assets/js/env.js:', e.message)
  }

  if (ready) {
    console.log('[FAS] Supabase configured — client will be active in the browser.')
  } else {
    console.log('[FAS] Supabase not configured — running in static preview mode.')
    console.log('[FAS]   To activate: set SUPABASE_URL and SUPABASE_ANON_KEY, then restart.')
  }
}


// ── STEP 2: MIME TYPE MAP ────────────────────────────────────────────
const MIME_TYPES = {
  '.html':  'text/html; charset=utf-8',
  '.css':   'text/css; charset=utf-8',
  '.js':    'application/javascript; charset=utf-8',
  '.json':  'application/json; charset=utf-8',
  '.svg':   'image/svg+xml',
  '.ico':   'image/x-icon',
  '.png':   'image/png',
  '.jpg':   'image/jpeg',
  '.jpeg':  'image/jpeg',
  '.gif':   'image/gif',
  '.webp':  'image/webp',
  '.avif':  'image/avif',
  '.woff':  'font/woff',
  '.woff2': 'font/woff2',
  '.ttf':   'font/ttf',
  '.otf':   'font/otf',
  '.mp4':   'video/mp4',
  '.mp3':   'audio/mpeg',
  '.ogg':   'audio/ogg',
  '.txt':   'text/plain; charset=utf-8',
  '.xml':   'application/xml',
  '.pdf':   'application/pdf',
}


// ── STEP 3: HTTP SERVER ──────────────────────────────────────────────
const server = http.createServer(handleRequest)

function handleRequest(req, res) {
  // Strip query strings and decode URI
  let urlPath
  try {
    urlPath = decodeURIComponent(req.url.split('?')[0])
  } catch {
    send(res, 400, 'text/plain', 'Bad Request')
    return
  }

  // ── API ROUTES (server-side, not static files) ─────────────
  // ── RADIO API ROUTES ───────────────────────────────────────────────
  if (urlPath.startsWith('/api/radio/')) {
    res.setHeader('Access-Control-Allow-Origin', '*')
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, DELETE, OPTIONS')
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-FAS-Username')
    if (req.method === 'OPTIONS') { send(res, 204, 'text/plain', ''); return }

    if (urlPath === '/api/radio/tracks') {
      if (req.method !== 'GET') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleRadioTracks(req, res)
      return
    }
    if (urlPath === '/api/radio/upload') {
      if (req.method !== 'POST') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleRadioUpload(req, res).catch(err => {
        console.error('[FAS:radio:upload] Unhandled error:', err.message)
        if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
      })
      return
    }
    if (urlPath === '/api/radio/delete') {
      if (req.method !== 'POST') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleRadioDelete(req, res).catch(err => {
        console.error('[FAS:radio:delete] Unhandled error:', err.message)
        if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
      })
      return
    }
    if (urlPath === '/api/radio/community-upload') {
      if (req.method !== 'POST') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleCommunityUpload(req, res).catch(err => {
        console.error('[FAS:community:upload] Unhandled error:', err.message)
        if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
      })
      return
    }


    sendJSON(res, 404, { error: 'Not found.' })
    return
  }

  if (urlPath.startsWith('/api/dm/')) {
    res.setHeader('Access-Control-Allow-Origin', '*')
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
    if (req.method === 'OPTIONS') { send(res, 204, 'text/plain', ''); return }

    if (urlPath === '/api/dm/upload') {
      if (req.method !== 'POST') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleDMUpload(req, res).catch(err => {
        console.error('[FAS:upload] Unhandled error:', err.message)
        if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
      })
      return
    }

    if (urlPath === '/api/dm/threads') {
      if (req.method !== 'GET') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleDMThreads(req, res).catch(err => {
        console.error('[FAS:dm:threads] Unhandled error:', err.message)
        if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
      })
      return
    }

    if (urlPath === '/api/dm/messages') {
      if (req.method !== 'GET') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleDMMessages(req, res).catch(err => {
        console.error('[FAS:dm:messages] Unhandled error:', err.message)
        if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
      })
      return
    }

    if (urlPath === '/api/dm/send') {
      if (req.method !== 'POST') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleDMSend(req, res).catch(err => {
        console.error('[FAS:dm:send] Unhandled error:', err.message)
        if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
      })
      return
    }

    if (urlPath === '/api/dm/mark-read') {
      if (req.method !== 'POST') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleDMMarkRead(req, res).catch(err => {
        console.error('[FAS:dm:mark-read] Unhandled error:', err.message)
        if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
      })
      return
    }

    sendJSON(res, 404, { error: 'Not found.' })
    return
  }

  // ── MUSIC UPLOAD API ─────────────────────────────────────────────────
  if (urlPath.startsWith('/api/music/')) {
    res.setHeader('Access-Control-Allow-Origin', '*')
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
    if (req.method === 'OPTIONS') { send(res, 204, 'text/plain', ''); return }

    if (urlPath === '/api/music/upload') {
      if (req.method !== 'POST') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleMusicUpload(req, res).catch(err => {
        console.error('[FAS:music:upload] Unhandled error:', err.message)
        if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
      })
      return
    }
    if (urlPath === '/api/music/delete') {
      if (req.method !== 'POST') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }
      handleMusicDelete(req, res).catch(err => {
        console.error('[FAS:music:delete] Unhandled error:', err.message)
        if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
      })
      return
    }

    sendJSON(res, 404, { error: 'Not found.' })
    return
  }

  // ── CONTACT FORM API ──────────────────────────────────────────────
  if (urlPath === '/api/admin/users/set-role') {
    res.setHeader('Access-Control-Allow-Origin', '*')
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
    if (req.method === 'OPTIONS') { send(res, 204, 'text/plain', ''); return }
    if (req.method !== 'POST') { sendJSON(res, 405, { ok: false, error: 'Method not allowed.', code: 'METHOD_NOT_ALLOWED' }); return }

    handleAdminSetRole(req, res).catch(err => {
      console.error('[FAS:admin:set-role] Unhandled error:', err.message)
      if (!res.headersSent) sendJSON(res, 500, { ok: false, error: 'Internal server error.', code: 'INTERNAL_ERROR' })
    })
    return
  }

  // ── CONTACT FORM API ──────────────────────────────────────────────
  if (urlPath === '/api/contact') {
    res.setHeader('Access-Control-Allow-Origin', '*')
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
    if (req.method === 'OPTIONS') { send(res, 204, 'text/plain', ''); return }
    if (req.method !== 'POST') { sendJSON(res, 405, { error: 'Method not allowed.' }); return }

    handleContactForm(req, res).catch(err => {
      console.error('[FAS:contact] Unhandled error:', err.message)
      if (!res.headersSent) sendJSON(res, 500, { error: 'Internal server error.' })
    })
    return
  }

  // Default to index.html
  if (urlPath === '/' || urlPath === '') {
    urlPath = '/index.html'
  }

  const parts = urlPath.replace(/^\//, '').split('/')

  // ── ADMIN ROUTES ─────────────────────────────────────────────
  // Admin files live under /admin/*.
  //
  // All /admin requests require a valid ADMIN_TOKEN env var and a
  // matching X-Admin-Token header. Without a valid token the request
  // is always blocked with 403 — there is no fallthrough to
  // client-side auth at the HTTP layer.
  //
  // To access the admin area:
  //   1. Set ADMIN_TOKEN in Replit Secrets (long random string).
  //   2. Add X-Admin-Token: <value> to browser requests (e.g. via
  //      a browser extension like ModHeader, or a Cloudflare
  //      Transform Rule / Access policy in production).
  //
  // Client-side auth (Supabase session + ADMIN_EMAILS allowlist in
  // admin-auth.js) provides a second independent layer of protection
  // once the page is loaded.
  if (urlPath.startsWith('/admin')) {
    console.log(`[FAS:admin] ${req.method} ${urlPath}`)
    const adminToken = process.env.ADMIN_TOKEN
    const provided   = req.headers['x-admin-token']

    if (!adminToken || !provided || provided !== adminToken) {
      send(res, 403, 'text/html; charset=utf-8',
        '<html><body style="font-family:system-ui;background:#0a0a0a;color:#f0f0f0;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;">' +
        '<div style="text-align:center;"><h1 style="color:#f87171;margin-bottom:0.5rem;">403 — Forbidden</h1>' +
        '<p style="color:#555;">You do not have permission to access this area.</p>' +
        '<p style="margin-top:1rem;"><a href="/" style="color:#c9a96e;">← Back to site</a></p>' +
        '</div></body></html>'
      )
      return
    }
  }

  // ── Dynamic creator/business page routing ─────────────────────
  // /artist/[slug]   → templates/artist.html
  // /creator/[slug]  → templates/creator.html
  // /business/[slug] → templates/business.html
  const routeType = parts[0]
  if (['artist', 'creator', 'business'].includes(routeType) && parts[1] && parts[1] !== '') {
    return serveFile(res, path.join(ROOT, 'templates', `${routeType}.html`))
  }

  const filePath = path.join(ROOT, urlPath)

  // Block directory traversal
  if (!filePath.startsWith(ROOT + path.sep) && filePath !== ROOT) {
    send(res, 403, 'text/plain', 'Forbidden')
    return
  }

  serveFile(res, filePath)
}

// ── ADMIN ROLE ACTIONS (trusted server path) ─────────────────────────
// Supports only:
//   - make_moderator  -> role: moderator
//   - remove_moderator -> role: user
async function handleAdminSetRole(req, res) {
  let rawBody
  try { rawBody = await readBody(req, 8192) } catch {
    return sendJSON(res, 400, { ok: false, error: 'Invalid request body.', code: 'INVALID_BODY' })
  }

  let body
  try { body = JSON.parse(rawBody.toString('utf8')) } catch {
    return sendJSON(res, 400, { ok: false, error: 'Invalid JSON body.', code: 'INVALID_JSON' })
  }

  const actorUsername = String(body && body.actor_username || '').toLowerCase().trim()
  const ph            = String(body && body.ph || '').trim()
  const targetUserId  = String(body && body.target_user_id || '').trim()
  const action        = String(body && body.action || '').toLowerCase().trim()

  if (!actorUsername || !ph || !targetUserId || !action) {
    return sendJSON(res, 400, { ok: false, error: 'Missing required fields.', code: 'MISSING_FIELDS' })
  }

  if (action !== 'make_moderator' && action !== 'remove_moderator') {
    return sendJSON(res, 400, { ok: false, error: 'Invalid action.', code: 'INVALID_ACTION' })
  }

  const actor = actorUsername.replace(/[^a-z0-9_-]/g, '')
  if (!actor) {
    return sendJSON(res, 400, { ok: false, error: 'Invalid actor username.', code: 'INVALID_ACTOR' })
  }

  let creds
  try { creds = getServiceCreds() } catch {
    return sendJSON(res, 503, { ok: false, error: 'Server not available.', code: 'SERVER_NOT_CONFIGURED' })
  }

  const ok = await verifyIdentity(creds.host, creds.key, actor, ph)
  if (!ok) {
    return sendJSON(res, 401, { ok: false, error: 'Authentication failed.', code: 'UNAUTHENTICATED' })
  }

  let actorRow = null
  try {
    const actorRes = await sbRequest(
      creds.host,
      creds.key,
      'GET',
      `/rest/v1/member_accounts?username=eq.${encodeURIComponent(actor)}&select=id,username,role&limit=1`,
      null
    )
    const rows = JSON.parse(actorRes.body.toString())
    actorRow = Array.isArray(rows) ? rows[0] : null
  } catch {}

  if (!actorRow) {
    return sendJSON(res, 403, { ok: false, error: 'Actor account not found.', code: 'ACTOR_NOT_FOUND' })
  }
  if (String(actorRow.role || 'user').toLowerCase() !== 'super_admin') {
    return sendJSON(res, 403, { ok: false, error: 'Only super_admin can change roles.', code: 'FORBIDDEN_NOT_SUPER_ADMIN' })
  }

  let targetRow = null
  try {
    const targetRes = await sbRequest(
      creds.host,
      creds.key,
      'GET',
      `/rest/v1/member_accounts?id=eq.${encodeURIComponent(targetUserId)}&select=id,username,role&limit=1`,
      null
    )
    const rows = JSON.parse(targetRes.body.toString())
    targetRow = Array.isArray(rows) ? rows[0] : null
  } catch {}

  if (!targetRow) {
    return sendJSON(res, 404, { ok: false, error: 'Target user not found.', code: 'TARGET_NOT_FOUND' })
  }

  if (String(targetRow.id || '') === String(actorRow.id || '')) {
    return sendJSON(res, 403, { ok: false, error: 'You cannot modify your own role.', code: 'FORBIDDEN_SELF_TARGET' })
  }

  const previousRole = String(targetRow.role || 'user').toLowerCase()
  if (previousRole === 'super_admin') {
    return sendJSON(res, 403, { ok: false, error: 'You cannot modify a super_admin account.', code: 'FORBIDDEN_TARGET_SUPER_ADMIN' })
  }

  const nextRole = action === 'make_moderator' ? 'moderator' : 'user'

  try {
    const updateRes = await sbRequest(
      creds.host,
      creds.key,
      'PATCH',
      `/rest/v1/member_accounts?id=eq.${encodeURIComponent(targetUserId)}`,
      JSON.stringify({ role: nextRole })
    )

    if (updateRes.status < 200 || updateRes.status >= 300) {
      return sendJSON(res, 500, { ok: false, error: 'Could not update role.', code: 'UPDATE_FAILED' })
    }
  } catch {
    return sendJSON(res, 500, { ok: false, error: 'Could not update role.', code: 'UPDATE_FAILED' })
  }

  sendJSON(res, 200, {
    ok: true,
    message: nextRole === 'moderator' ? 'User updated to moderator.' : 'Moderator role removed.',
    action,
    target: {
      id: targetRow.id,
      username: targetRow.username,
      previous_role: previousRole,
      next_role: nextRole,
    },
  })
}

function serveFile(res, filePath) {
  fs.readFile(filePath, (err, data) => {
    if (!err) {
      const ext  = path.extname(filePath).toLowerCase()
      const mime = MIME_TYPES[ext] || 'application/octet-stream'
      res.writeHead(200, {
        'Content-Type':  mime,
        'Cache-Control': 'no-cache',
      })
      res.end(data)
      return
    }

    if (err.code === 'ENOENT') {
      // Try appending .html (e.g. /about → /about.html)
      if (!path.extname(filePath)) {
        return serveFile(res, filePath + '.html')
      }
      send(res, 404, 'text/html; charset=utf-8',
        '<h1 style="font-family:system-ui">404 — Not Found</h1>')
    } else if (err.code === 'EISDIR') {
      // Directory requested — serve index.html inside it
      return serveFile(res, path.join(filePath, 'index.html'))
    } else {
      send(res, 500, 'text/plain', 'Internal Server Error')
    }
  })
}

function send(res, status, type, body) {
  res.writeHead(status, { 'Content-Type': type })
  res.end(body)
}

// ── RADIO TRACK HANDLERS ─────────────────────────────────────────────

const AUDIO_DIR   = path.join(ROOT, 'assets', 'audio')
const RADIO_ADMINS = new Set(['jamespropane00', 'arianamnm'])   // usernames with radio upload/delete access
const RADIO_MAX_BYTES = 60 * 1024 * 1024  // 60MB body limit (50MB file + base64 overhead)
const RADIO_MAX_FILE  = 50 * 1024 * 1024  // 50MB per track
const RADIO_ALLOWED   = new Set([
  'audio/mpeg', 'audio/ogg', 'audio/wav', 'audio/flac', 'audio/mp4',
  'audio/x-m4a', 'audio/aiff', 'audio/aac',
])

// Channel config: ch1 keeps existing paths for backward compat; ch4/ch5 get their own dirs
const CHANNELS = {
  '1': { dir: AUDIO_DIR,                                  json: path.join(AUDIO_DIR, 'tracks.json')   },
  '4': { dir: path.join(AUDIO_DIR, 'ch4'),                json: path.join(AUDIO_DIR, 'tracks-4.json') },
  '5': { dir: path.join(AUDIO_DIR, 'ch5'),                json: path.join(AUDIO_DIR, 'tracks-5.json') },
}

function getChannel(ch) {
  return CHANNELS[ch] || CHANNELS['1']
}

function readChannelTracks(ch) {
  const { json } = getChannel(ch)
  try { return JSON.parse(fs.readFileSync(json, 'utf8')) } catch { return [] }
}

function writeChannelTracks(tracks, ch) {
  const { json, dir } = getChannel(ch)
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(json, JSON.stringify(tracks, null, 2), 'utf8')
}

/** GET /api/radio/tracks?channel=1|4|5 — public, returns track list for a channel */
function handleRadioTracks(req, res) {
  const u   = new URL(req.url, 'http://localhost')
  const ch  = CHANNELS[u.searchParams.get('channel')] ? u.searchParams.get('channel') : '1'
  sendJSON(res, 200, { tracks: readChannelTracks(ch), channel: ch })
}

/** POST /api/radio/upload — admin only, saves audio file + updates channel tracks */
async function handleRadioUpload(req, res) {
  let rawBody
  try {
    rawBody = await readBody(req, RADIO_MAX_BYTES)
  } catch {
    return sendJSON(res, 413, { error: 'File too large. Max 50MB.' })
  }

  let body
  try { body = JSON.parse(rawBody.toString('utf8')) } catch {
    return sendJSON(res, 400, { error: 'Invalid JSON body.' })
  }

  const { username, ph, file_b64, file_type, file_name, title, channel } = body
  const ch = CHANNELS[channel] ? String(channel) : '1'

  if (!username || !ph || !file_b64 || !file_type || !file_name || !title) {
    return sendJSON(res, 400, { error: 'Missing required fields.' })
  }

  const u = username.toLowerCase().replace(/[^a-z0-9_]/g, '')
  if (!RADIO_ADMINS.has(u)) {
    return sendJSON(res, 403, { error: 'Admin access only.' })
  }

  if (!RADIO_ALLOWED.has(file_type)) {
    return sendJSON(res, 400, { error: 'Only audio files are allowed (mp3, wav, ogg, flac, m4a, aac).' })
  }

  let creds
  try { creds = getServiceCreds() } catch {
    return sendJSON(res, 503, { error: 'Server not configured with service credentials.' })
  }

  const ok = await verifyIdentity(creds.host, creds.key, u, ph)
  if (!ok) return sendJSON(res, 401, { error: 'Authentication failed.' })

  let fileBuffer
  try { fileBuffer = Buffer.from(file_b64, 'base64') } catch {
    return sendJSON(res, 400, { error: 'Could not decode file data.' })
  }
  if (fileBuffer.length > RADIO_MAX_FILE) {
    return sendJSON(res, 400, { error: 'File exceeds 50MB limit.' })
  }

  const { dir } = getChannel(ch)
  const ext      = path.extname(file_name).toLowerCase() || '.mp3'
  const safeName = (path.basename(file_name, ext) || 'track').replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 60)
  const fileName = Date.now() + '_' + safeName + ext
  const filePath = path.join(dir, fileName)
  const srcPath  = ch === '1' ? 'assets/audio/' + fileName : 'assets/audio/ch' + ch + '/' + fileName

  try {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true })
    fs.writeFileSync(filePath, fileBuffer)
  } catch (e) {
    console.error('[FAS:radio:upload] File write error:', e.message)
    return sendJSON(res, 500, { error: 'Could not save file.' })
  }

  const tracks = readChannelTracks(ch)
  const entry  = { id: fileName, title: title.trim().slice(0, 100), src: srcPath, uploadedAt: new Date().toISOString() }
  tracks.push(entry)
  try { writeChannelTracks(tracks, ch) } catch (e) {
    console.error('[FAS:radio:upload] tracks write error:', e.message)
    return sendJSON(res, 500, { error: 'File saved but track list could not be updated.' })
  }

  console.log('[FAS:radio:upload] Channel', ch, 'uploaded:', fileName, '(' + fileBuffer.length + ' bytes)')
  sendJSON(res, 200, { ok: true, track: entry, channel: ch })
}

/** POST /api/radio/delete — admin only, removes track from channel + disk */
async function handleRadioDelete(req, res) {
  let rawBody
  try { rawBody = await readBody(req, 4096) } catch {
    return sendJSON(res, 400, { error: 'Bad request.' })
  }

  let body
  try { body = JSON.parse(rawBody.toString('utf8')) } catch {
    return sendJSON(res, 400, { error: 'Invalid JSON body.' })
  }

  const { username, ph, id, channel } = body
  const ch = CHANNELS[channel] ? String(channel) : '1'
  if (!username || !ph || !id) return sendJSON(res, 400, { error: 'Missing fields.' })

  const u = username.toLowerCase().replace(/[^a-z0-9_]/g, '')
  if (!RADIO_ADMINS.has(u)) return sendJSON(res, 403, { error: 'Admin access only.' })

  let creds
  try { creds = getServiceCreds() } catch {
    return sendJSON(res, 503, { error: 'Server not configured.' })
  }

  const ok = await verifyIdentity(creds.host, creds.key, u, ph)
  if (!ok) return sendJSON(res, 401, { error: 'Authentication failed.' })

  const safeId = path.basename(id)
  const tracks = readChannelTracks(ch)
  const idx    = tracks.findIndex(t => t.id === safeId)
  if (idx === -1) return sendJSON(res, 404, { error: 'Track not found.' })

  tracks.splice(idx, 1)
  try { writeChannelTracks(tracks, ch) } catch (e) {
    return sendJSON(res, 500, { error: 'Could not update track list.' })
  }

  const { dir } = getChannel(ch)
  try { fs.unlinkSync(path.join(dir, safeId)) } catch { /* file may already be gone — ok */ }

  console.log('[FAS:radio:delete] Channel', ch, 'deleted track:', safeId)
  sendJSON(res, 200, { ok: true })
}

// ── COMMUNITY RADIO UPLOAD ───────────────────────────────────────────
//  Members with an active paid plan can upload audio directly to
//  Station 1.  Limit: 2 tracks per calendar month per member.
//  Files are saved to assets/audio/community/ and appended to tracks.json.

const COMMUNITY_AUDIO_DIR      = path.join(AUDIO_DIR, 'community')
const COMMUNITY_MAX_FILE_MB    = 30
const COMMUNITY_MAX_FILE_B     = COMMUNITY_MAX_FILE_MB * 1024 * 1024
const COMMUNITY_MAX_PER_MONTH  = 2
const COMMUNITY_PAID_PLANS     = new Set(['access', 'starter', 'pro', 'premium'])

/** POST /api/radio/community-upload — paid members, max 2/month, goes to Station 1 */
async function handleCommunityUpload(req, res) {
  let rawBody
  try {
    rawBody = await readBody(req, COMMUNITY_MAX_FILE_B + 16384)
  } catch {
    return sendJSON(res, 413, { error: `File too large. Max ${COMMUNITY_MAX_FILE_MB}MB.` })
  }

  let body
  try { body = JSON.parse(rawBody.toString('utf8')) } catch {
    return sendJSON(res, 400, { error: 'Invalid request body.' })
  }

  const { username, ph, file_b64, file_type, file_name, title } = body
  if (!username || !ph || !file_b64 || !file_type || !file_name || !title) {
    return sendJSON(res, 400, { error: 'Missing required fields (username, ph, file_b64, file_type, file_name, title).' })
  }

  const u = username.toLowerCase().replace(/[^a-z0-9_-]/g, '')
  if (!u) return sendJSON(res, 400, { error: 'Invalid username.' })

  if (!RADIO_ALLOWED.has(file_type)) {
    return sendJSON(res, 400, { error: 'Only audio files supported (MP3, WAV, OGG, FLAC, M4A, AAC).' })
  }

  let creds
  try { creds = getServiceCreds() } catch {
    return sendJSON(res, 503, { error: 'Server not available.' })
  }

  const ok = await verifyIdentity(creds.host, creds.key, u, ph)
  if (!ok) return sendJSON(res, 401, { error: 'Authentication failed. Sign in again.' })

  // Check paid plan from DB (server-side, not just session)
  let planOk = false
  try {
    const planRes = await sbRequest(creds.host, creds.key, 'GET',
      `/rest/v1/member_accounts?username=eq.${encodeURIComponent(u)}&select=plan_type,member_status`, null)
    const rows = JSON.parse(planRes.body.toString())
    if (Array.isArray(rows) && rows.length > 0) {
      const { plan_type, member_status } = rows[0]
      planOk = COMMUNITY_PAID_PLANS.has(plan_type) && member_status === 'active'
    }
  } catch {}
  if (!planOk) return sendJSON(res, 403, { error: 'Active paid membership required to upload tracks to Station 1.' })

  // Monthly quota from Supabase source-of-truth table.
  const now = new Date()
  const monthStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1, 0, 0, 0)).toISOString()
  const nextMonthStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1, 0, 0, 0)).toISOString()

  let monthCount = 0
  try {
    const quotaRes = await sbRequest(
      creds.host,
      creds.key,
      'GET',
      `/rest/v1/radio_upload_quota?username=eq.${encodeURIComponent(u)}&uploaded_at=gte.${encodeURIComponent(monthStart)}&uploaded_at=lt.${encodeURIComponent(nextMonthStart)}&select=id`,
      null
    )
    const rows = JSON.parse(quotaRes.body.toString())
    monthCount = Array.isArray(rows) ? rows.length : 0
  } catch {
    return sendJSON(res, 500, { error: 'Could not check monthly quota. Please try again.' })
  }

  if (monthCount >= COMMUNITY_MAX_PER_MONTH) {
    return sendJSON(res, 429, { error: 'You have already used your 2 uploads for this month.' })
  }

  let fileBuffer
  try { fileBuffer = Buffer.from(file_b64, 'base64') } catch {
    return sendJSON(res, 400, { error: 'Could not decode file data.' })
  }
  if (fileBuffer.length > COMMUNITY_MAX_FILE_B) {
    return sendJSON(res, 400, { error: `File exceeds ${COMMUNITY_MAX_FILE_MB}MB limit.` })
  }

  // Upload to Supabase Storage bucket so metadata remains canonical in Supabase.
  const ext      = path.extname(file_name).toLowerCase() || '.mp3'
  const safeName = (path.basename(file_name, ext) || 'track').replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 60)
  const fileName = Date.now() + '_' + u + '_' + safeName + ext
  const storagePath = 'ch1/community/' + fileName
  const publicSrc = `https://${creds.host}/storage/v1/object/public/radio/${storagePath}`

  try {
    const upload = await sbStorageUpload(
      creds.host,
      creds.key,
      'radio',
      storagePath,
      file_type,
      fileBuffer,
      false
    )
    if (upload.status < 200 || upload.status >= 300) {
      return sendJSON(res, 500, { error: 'Could not upload your track to storage. Try again.' })
    }
  } catch (e) {
    console.error('[FAS:community:upload] storage upload error:', e.message)
    return sendJSON(res, 500, { error: 'Could not save your track. Try again.' })
  }

  let trackEntry = null
  try {
    const ins = await sbRequest(
      creds.host,
      creds.key,
      'POST',
      '/rest/v1/radio_tracks',
      JSON.stringify([{
        channel: '1',
        title: title.trim().slice(0, 100) + ' · @' + u,
        src: publicSrc,
        storage_path: storagePath,
        uploaded_by: u,
        is_active: true,
      }])
    )
    if (ins.status < 200 || ins.status >= 300) {
      console.error('[FAS:community:upload] radio_tracks insert failed:', ins.body.toString())
      return sendJSON(res, 500, { error: 'Track upload succeeded but metadata save failed.' })
    }
    const rows = JSON.parse(ins.body.toString())
    trackEntry = Array.isArray(rows) && rows.length ? rows[0] : null

    const quotaIns = await sbRequest(
      creds.host,
      creds.key,
      'POST',
      '/rest/v1/radio_upload_quota',
      JSON.stringify([{
        username: u,
        station: '1',
        title: title.trim().slice(0, 100),
        storage_path: storagePath,
      }])
    )
    if (quotaIns.status < 200 || quotaIns.status >= 300) {
      console.error('[FAS:community:upload] radio_upload_quota insert failed:', quotaIns.body.toString())
      return sendJSON(res, 500, { error: 'Track uploaded but quota write failed.' })
    }
  } catch (e) {
    console.error('[FAS:community:upload] metadata write error:', e.message)
    return sendJSON(res, 500, { error: 'Could not finalize upload metadata.' })
  }

  console.log('[FAS:community:upload]', u, 'uploaded:', fileName,
    `(${fileBuffer.length} bytes, month ${monthCount + 1}/${COMMUNITY_MAX_PER_MONTH})`)

  const nextCount = monthCount + 1
  const remaining = Math.max(0, COMMUNITY_MAX_PER_MONTH - nextCount)

  sendJSON(res, 200, {
    ok:        true,
    track:     trackEntry,
    monthCount: nextCount,
    remaining:  remaining,
  })
}

// ── DM FILE UPLOAD HANDLER ───────────────────────────────────────────
//
// Security model:
//   1. Browser sends { username, ph, file_b64, file_type, file_name, file_size }
//   2. Server verifies `ph` (PBKDF2 hash) via Supabase RPC — proves identity
//   3. Server checks member plan via service_role — must be active/paid
//   4. Server uploads binary to Supabase Storage via service_role (bypasses RLS)
//   5. Server generates a 24-hour signed URL and returns it
//
// The SUPABASE_SERVICE_ROLE_KEY NEVER reaches the browser.
// The anon key NEVER touches Storage.
// No anon or authenticated storage policies are required on the bucket.
// The bucket should remain private with no policies (service_role only).

const UPLOAD_BUCKET     = 'dm-attachments'
const UPLOAD_MAX_BYTES  = 15 * 1024 * 1024   // 15MB body limit (10MB file + base64 overhead)
const UPLOAD_MAX_FILE_B = 10 * 1024 * 1024
const UPLOAD_ALLOWED    = new Set([
  'image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/avif',
  'audio/mpeg', 'audio/ogg', 'audio/wav', 'audio/flac', 'audio/mp4',
  'audio/x-m4a', 'audio/aiff',
  'video/mp4', 'video/webm',
  'application/pdf', 'text/plain',
])

async function handleDMUpload(req, res) {
  const SERVICE_KEY  = process.env.SUPABASE_SERVICE_ROLE_KEY
  const SUPA_URL     = process.env.SUPABASE_URL

  if (!SERVICE_KEY || !SUPA_URL) {
    console.warn('[FAS:upload] SUPABASE_SERVICE_ROLE_KEY is not set — /api/dm/upload unavailable.')
    return sendJSON(res, 503, { error: 'File uploads are not configured on this server. Set SUPABASE_SERVICE_ROLE_KEY.' })
  }

  // Parse hostname for https.request (strip https://)
  let supabaseHost
  try {
    supabaseHost = new URL(SUPA_URL).hostname
  } catch {
    return sendJSON(res, 503, { error: 'Invalid SUPABASE_URL configuration.' })
  }

  // ── 1. Read body ────────────────────────────────────────────
  let rawBody
  try {
    rawBody = await readBody(req, UPLOAD_MAX_BYTES)
  } catch (e) {
    return sendJSON(res, 413, { error: 'Request too large. Max file size is 10MB.' })
  }

  let body
  try {
    body = JSON.parse(rawBody.toString('utf8'))
  } catch {
    return sendJSON(res, 400, { error: 'Invalid JSON body.' })
  }

  const { username, ph, file_b64, file_type, file_name, file_size } = body

  // ── 2. Validate fields ──────────────────────────────────────
  if (!username || !ph || !file_b64 || !file_type || !file_name) {
    return sendJSON(res, 400, { error: 'Missing required fields.' })
  }
  if (typeof file_size === 'number' && file_size > UPLOAD_MAX_FILE_B) {
    return sendJSON(res, 400, { error: 'File too large. Maximum is 10MB.' })
  }
  if (!UPLOAD_ALLOWED.has(file_type)) {
    return sendJSON(res, 400, { error: 'File type not allowed.' })
  }
  const u = username.toLowerCase().replace(/[^a-z0-9_]/g, '')
  if (!u || u.length < 3 || u.length > 30) {
    return sendJSON(res, 400, { error: 'Invalid username.' })
  }

  // ── 3. Verify identity via Supabase RPC ─────────────────────
  // verify_member_password(p_username, p_hash) → bool
  // Uses service_role to bypass RLS — no anon policy needed.
  const verifyResult = await sbRequest(supabaseHost, SERVICE_KEY, 'POST',
    '/rest/v1/rpc/verify_member_password',
    JSON.stringify({ p_username: u, p_hash: ph })
  )

  if (verifyResult.status !== 200) {
    console.error('[FAS:upload] RPC error:', verifyResult.status, verifyResult.body.toString())
    return sendJSON(res, 500, { error: 'Could not verify identity. Try again.' })
  }

  let verified
  try { verified = JSON.parse(verifyResult.body.toString()) } catch { verified = false }
  if (!verified) {
    return sendJSON(res, 401, { error: 'Authentication failed. Please sign in again.' })
  }

  // ── 4. Check member plan ────────────────────────────────────
  const planResult = await sbRequest(supabaseHost, SERVICE_KEY, 'GET',
    `/rest/v1/member_accounts?username=eq.${encodeURIComponent(u)}&select=plan_type,member_status`,
    null
  )

  let member = null
  try {
    const rows = JSON.parse(planResult.body.toString())
    member = Array.isArray(rows) ? rows[0] : null
  } catch {}

  const activePlan = member && !['free', 'none'].includes(member.plan_type || '') && member.member_status !== 'inactive'
  if (!activePlan) {
    return sendJSON(res, 403, { error: 'File attachments require an active paid plan. Upgrade at facelessanimalstudios.com/pricing.' })
  }

  // ── 5. Decode base64 → binary Buffer ───────────────────────
  let fileBuffer
  try {
    fileBuffer = Buffer.from(file_b64, 'base64')
  } catch {
    return sendJSON(res, 400, { error: 'Could not decode file data.' })
  }
  if (fileBuffer.length > UPLOAD_MAX_FILE_B) {
    return sendJSON(res, 400, { error: 'Decoded file exceeds 10MB limit.' })
  }

  // ── 6. Upload to Supabase Storage via service_role ──────────
  const safeName    = (file_name || 'file').replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 60)
  const storagePath = `${u}/${Date.now()}_${safeName}`

  const uploadResult = await sbStorageUpload(supabaseHost, SERVICE_KEY, UPLOAD_BUCKET, storagePath, file_type, fileBuffer)
  if (uploadResult.status !== 200 && uploadResult.status !== 201) {
    const errBody = uploadResult.body.toString()
    console.error(`[FAS:upload] Storage PUT failed (${uploadResult.status}):`, errBody)
    return sendJSON(res, 500, { error: 'File upload failed. Try again.' })
  }

  // ── 7. Generate signed URL (24h) ────────────────────────────
  const signResult = await sbRequest(supabaseHost, SERVICE_KEY, 'POST',
    `/storage/v1/object/sign/${UPLOAD_BUCKET}/${storagePath}`,
    JSON.stringify({ expiresIn: 86400 })
  )

  let signedUrl = null
  try {
    const signData = JSON.parse(signResult.body.toString())
    const raw = signData.signedURL || signData.signedUrl || ''
    signedUrl = raw.startsWith('http') ? raw : `${SUPA_URL}/storage/v1${raw}`
  } catch {}

  if (!signedUrl) {
    return sendJSON(res, 500, { error: 'Upload succeeded but could not generate download link.' })
  }

  console.log(`[FAS:upload] ${u} uploaded ${safeName} (${fileBuffer.length} bytes)`)
  return sendJSON(res, 200, { url: signedUrl, path: storagePath, error: null })
}

// ── CONTACT FORM HANDLER ──────────────────────────────────────────────
async function handleContactForm(req, res) {
  const bodyBuf = await readBody(req, 64 * 1024) // 64KB max
  let body = {}
  const ct = (req.headers['content-type'] || '').split(';')[0].trim()

  if (ct === 'application/json') {
    try { body = JSON.parse(bodyBuf.toString('utf8')) } catch (e) {
      return sendJSON(res, 400, { error: 'Invalid JSON.' })
    }
  } else if (ct === 'application/x-www-form-urlencoded') {
    const params = new URLSearchParams(bodyBuf.toString('utf8'))
    for (const [k, v] of params) body[k] = v
  } else {
    return sendJSON(res, 415, { error: 'Unsupported content type.' })
  }

  const name    = (body.name    || '').trim().slice(0, 200)
  const email   = (body.email   || '').trim().slice(0, 200)
  const type    = (body.type    || body.request_type || body.subject || body.package || '').trim().slice(0, 200)
  const message = (body.message || body.details || body.description || body.bio || '').trim().slice(0, 5000)
  const social  = (body.social  || body.social_handle || body.instagram || '').trim().slice(0, 200)
  const page    = (body.page    || body.source || 'unknown').trim()

  if (!name || !email) {
    return sendJSON(res, 400, { error: 'Name and email are required.' })
  }
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return sendJSON(res, 400, { error: 'Invalid email address.' })
  }

  // Store in Supabase submissions table
  const sbHost = process.env.SUPABASE_URL.replace('https://', '')
  const sbKey  = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY

  // Capture any extra form fields not already mapped
  const { name: _n, email: _e, type: _t, request_type: _rt, subject: _s, package: _pkg,
          message: _m, details: _d, description: _dd, bio: _b,
          social: _so, social_handle: _sh, instagram: _ig, page: _pg, source: _src, ...rest } = body
  const extra  = JSON.stringify({ type, social, page, ...rest })

  const payload = JSON.stringify({
    submission_type: 'contact_inquiry',
    display_name:    name,
    username:        email,
    bio:             message,
    extra_notes:     extra,
    status:          'submitted',
    links_json:      [],
    selected_plan:   'none',
    payment_verified: false,
  })

  let saved = false
  try {
    const r = await sbRequest(sbHost, sbKey, 'POST', '/rest/v1/submissions', payload)
    saved = r.status >= 200 && r.status < 300
    if (!saved) console.error(`[FAS:contact] DB save failed (status ${r.status}) for ${email}`)
  } catch (e) {
    console.error(`[FAS:contact] DB error: ${e.message}`)
  }

  if (!saved) {
    console.log(`[FAS:contact] Fallback log — From: ${name} <${email}> — ${type} — ${message.slice(0, 100)}`)
  } else {
    console.log(`[FAS:contact] Inquiry from ${email} (${name}) stored.`)
  }

  return sendJSON(res, 200, { ok: true, message: 'Inquiry received.' })
}


// ── Server helpers ────────────────────────────────────────────────────

function readBody(req, maxBytes) {
  return new Promise((resolve, reject) => {
    const chunks = []
    let total = 0
    req.on('data', chunk => {
      total += chunk.length
      if (total > maxBytes) { reject(new Error('Body too large')); req.destroy(); return }
      chunks.push(chunk)
    })
    req.on('end', () => resolve(Buffer.concat(chunks)))
    req.on('error', reject)
  })
}

function sendJSON(res, status, data) {
  const body = JSON.stringify(data)
  res.writeHead(status, { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) })
  res.end(body)
}

// Generic Supabase REST/RPC request (JSON body)
function sbRequest(host, serviceKey, method, urlPath, jsonBody) {

  // Best-effort member activity write for server-authoritative events.
  async function recordMemberActivityServer(host, serviceKey, evt) {
    try {
      const username = String(evt && evt.username || '').toLowerCase().trim()
      const actionType = String(evt && evt.actionType || '').trim()
      if (!username || !actionType) return false

      const pagePath = evt && evt.pagePath ? String(evt.pagePath) : null
      const source = evt && evt.source ? String(evt.source) : 'server'
      const refId = evt && evt.refId ? String(evt.refId) : null
      const momentumDelta = Math.max(0, Number(evt && evt.momentumDelta || 1))
      const context = evt && evt.context && typeof evt.context === 'object' ? evt.context : {}
      const nowIso = new Date().toISOString()

      await sbRequest(
        host,
        serviceKey,
        'PATCH',
        `/rest/v1/member_accounts?username=eq.${encodeURIComponent(username)}`,
        JSON.stringify({ last_active_at: nowIso })
      )

      let currentMomentum = 0
      try {
        const mRes = await sbRequest(
          host,
          serviceKey,
          'GET',
          `/rest/v1/member_accounts?username=eq.${encodeURIComponent(username)}&select=momentum&limit=1`,
          null
        )
        const mRows = JSON.parse(mRes.body.toString())
        if (Array.isArray(mRows) && mRows.length) {
          currentMomentum = Number(mRows[0].momentum || 0)
        }
      } catch {}

      await sbRequest(
        host,
        serviceKey,
        'PATCH',
        `/rest/v1/member_accounts?username=eq.${encodeURIComponent(username)}`,
        JSON.stringify({
          momentum: Math.max(0, currentMomentum + momentumDelta),
          last_active_at: nowIso,
        })
      )

      await sbRequest(
        host,
        serviceKey,
        'POST',
        '/rest/v1/activity_log',
        JSON.stringify([{
          username,
          action_type: actionType,
          page_path: pagePath,
          context_json: context,
          source,
          ref_id: refId,
        }])
      )

      return true
    } catch (err) {
      console.info('[FAS] activity log skipped:', err && err.message ? err.message : err)
      return false
    }
  }
  return new Promise((resolve, reject) => {
    const bodyBuf = jsonBody ? Buffer.from(jsonBody, 'utf8') : null
    const headers = {
      'apikey':        serviceKey,
      'Authorization': `Bearer ${serviceKey}`,
      'Content-Type':  'application/json',
      'Prefer':        'return=representation',

      await recordMemberActivityServer(creds.host, creds.key, {
        username: u,
        actionType: 'radio_upload_success',
        pagePath: '/radio.html',
        source: 'server_local',
        refId: (trackEntry && trackEntry.id) ? String(trackEntry.id) : storagePath,
        momentumDelta: 1,
        context: { station: '1' },
      })
    }
    if (bodyBuf) headers['Content-Length'] = bodyBuf.length

    const opts = { hostname: host, port: 443, path: urlPath, method, headers }
    const req  = https.request(opts, res => {
      const chunks = []
      res.on('data', d => chunks.push(d))
      res.on('end', () => resolve({ status: res.statusCode, body: Buffer.concat(chunks) }))
    })
    req.on('error', reject)
    if (bodyBuf) req.write(bodyBuf)
    req.end()
  })
}

// Supabase Storage binary upload (PUT with raw buffer body)
// Pass upsert=true to overwrite an existing file (e.g. _index.json)
function sbStorageUpload(host, serviceKey, bucket, storagePath, contentType, buffer, upsert = false) {
  return new Promise((resolve, reject) => {
    const headers = {
      'Authorization': `Bearer ${serviceKey}`,
      'Content-Type':  contentType,
      'Content-Length': buffer.length,
      'x-upsert':      upsert ? 'true' : 'false',
    }
    const opts = {
      hostname: host, port: 443,
      path:     `/storage/v1/object/${bucket}/${storagePath}`,
      method:   'PUT',
      headers,
    }
    const req = https.request(opts, res => {
      const chunks = []
      res.on('data', d => chunks.push(d))
      res.on('end', () => resolve({ status: res.statusCode, body: Buffer.concat(chunks) }))
    })
    req.on('error', reject)
    req.write(buffer)
    req.end()
  })
}

// ═══════════════════════════════════════════════════════════════
//  SERVER-PROXIED DM ENDPOINTS
//
//  All DM read/write operations are gated through the Express server
//  using the SUPABASE_SERVICE_ROLE_KEY (never exposed to the browser).
//  Every endpoint validates the caller's identity by checking the
//  password_hash against member_accounts before returning any data.
//
//  This is required because the platform uses custom password auth
//  rather than Supabase Auth JWT — without a JWT there is no way to
//  enforce per-user RLS at the Supabase level using the anon key.
//
//  Security model:
//    1. Client sends { username, ph } with every DM request.
//    2. Server queries member_accounts WHERE username = ? AND password_hash = ?
//       using the service_role key (bypasses RLS, trusted server-only).
//    3. If identity check fails → 401 Unauthorized.
//    4. Verified requests are served/written using service_role, so the
//       anon key is NEVER used on the dm_messages table.
//    5. anon role SELECT/INSERT/UPDATE on dm_messages is revoked in
//       migration 015_dm_messages_rls_lockdown.sql.
// ═══════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════
//  MUSIC UPLOAD ENDPOINTS
//  POST /api/music/upload  — authenticated track upload to creator-media bucket
//  POST /api/music/delete  — authenticated track delete from creator-media bucket
// ═══════════════════════════════════════════════════════════════

const MUSIC_BUCKET     = 'creator-media'
const MUSIC_MAX_BYTES  = 42 * 1024 * 1024   // 42MB body (30MB file + base64 overhead)
const MUSIC_MAX_FILE   = 30 * 1024 * 1024   // 30MB decoded
const MUSIC_MAX_TRACKS = 10                  // max tracks per member (server-enforced)
const MUSIC_ALLOWED   = new Set([
  'audio/mpeg', 'audio/mp3', 'audio/ogg', 'audio/wav', 'audio/x-wav',
  'audio/flac', 'audio/mp4', 'audio/x-m4a', 'audio/aiff', 'audio/x-aiff',
  'audio/aac', 'audio/webm',
])

async function handleMusicUpload(req, res) {
  const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY
  const SUPA_URL    = process.env.SUPABASE_URL
  if (!SERVICE_KEY || !SUPA_URL) {
    return sendJSON(res, 503, { error: 'File uploads are not configured on this server.' })
  }
  let supabaseHost
  try { supabaseHost = new URL(SUPA_URL).hostname } catch {
    return sendJSON(res, 503, { error: 'Invalid SUPABASE_URL configuration.' })
  }

  let rawBody
  try { rawBody = await readBody(req, MUSIC_MAX_BYTES) } catch {
    return sendJSON(res, 413, { error: 'File too large. Max 30MB per track.' })
  }

  let body
  try { body = JSON.parse(rawBody.toString('utf8')) } catch {
    return sendJSON(res, 400, { error: 'Invalid JSON body.' })
  }

  const { username, ph, file_b64, file_type, file_name, file_size, title, description } = body
  if (!username || !ph || !file_b64 || !file_type || !file_name || !title) {
    return sendJSON(res, 400, { error: 'Missing required fields.' })
  }
  if (!(title || '').trim()) return sendJSON(res, 400, { error: 'Track title is required.' })
  if (!MUSIC_ALLOWED.has(file_type)) {
    return sendJSON(res, 400, { error: 'Only audio files allowed (MP3, WAV, FLAC, OGG, M4A, AAC).' })
  }
  if (typeof file_size === 'number' && file_size > MUSIC_MAX_FILE) {
    return sendJSON(res, 400, { error: 'File too large. Max 30MB per track.' })
  }

  const u = username.toLowerCase().replace(/[^a-z0-9_-]/g, '')
  if (!u) return sendJSON(res, 400, { error: 'Invalid username.' })

  // Verify identity
  let creds
  try { creds = getServiceCreds() } catch {
    return sendJSON(res, 503, { error: 'Server credentials not configured.' })
  }
  const ok = await verifyIdentity(creds.host, creds.key, u, ph)
  if (!ok) return sendJSON(res, 401, { error: 'Authentication failed. Sign in again.' })

  // Check paid plan
  const planResult = await sbRequest(creds.host, creds.key, 'GET',
    `/rest/v1/member_accounts?username=eq.${encodeURIComponent(u)}&select=plan_type,member_status`, null)
  let member = null
  try { const rows = JSON.parse(planResult.body.toString()); member = Array.isArray(rows) ? rows[0] : null } catch {}
  const hasAccess = member &&
    !['free', 'none', ''].includes((member.plan_type || '').toLowerCase()) &&
    member.member_status !== 'inactive'
  if (!hasAccess) {
    return sendJSON(res, 403, { error: 'Music upload requires an active paid plan.' })
  }

  // Decode base64 → buffer
  let fileBuffer
  try { fileBuffer = Buffer.from(file_b64, 'base64') } catch {
    return sendJSON(res, 400, { error: 'Could not decode file data.' })
  }
  if (fileBuffer.length > MUSIC_MAX_FILE) {
    return sendJSON(res, 400, { error: 'Decoded file exceeds 30MB limit.' })
  }

  // Build storage path under creator-media/{username}/tracks/
  const extMatch = (file_name || '').match(/\.[^.]+$/)
  const ext      = extMatch ? extMatch[0].toLowerCase() : '.mp3'
  const baseName = (file_name || 'track').replace(/\.[^.]+$/, '').replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 60)
  const storagePath = `${u}/tracks/${Date.now()}_${baseName}${ext}`

  // Upload to creator-media bucket (public read)
  const uploadResult = await sbStorageUpload(supabaseHost, SERVICE_KEY, MUSIC_BUCKET, storagePath, file_type, fileBuffer)
  if (uploadResult.status !== 200 && uploadResult.status !== 201) {
    console.error('[FAS:music:upload] Storage error:', uploadResult.status, uploadResult.body.toString().slice(0, 300))
    return sendJSON(res, 500, { error: 'Upload failed. Try again.' })
  }

  // Public URL (bucket is public, no signed URL needed)
  const publicUrl = `${SUPA_URL}/storage/v1/object/public/${MUSIC_BUCKET}/${storagePath}`

  const newTrack = {
    id:          storagePath,
    title:       title.trim(),
    description: (description || '').trim().slice(0, 200),
    url:         publicUrl,
    path:        storagePath,
    size:        fileBuffer.length,
    uploaded_at: new Date().toISOString(),
  }

  // Update _index.json in Storage so client can fetch the list without a DB column
  const indexPath = `${u}/tracks/_index.json`
  let currentIndex = []
  try {
    const fetchRes = await sbRequest(supabaseHost, SERVICE_KEY, 'GET',
      `/storage/v1/object/${MUSIC_BUCKET}/${indexPath}`, null)
    if (fetchRes.status === 200) currentIndex = JSON.parse(fetchRes.body.toString('utf8'))
  } catch { /* first upload — no index yet */ }
  const updatedIndex = [newTrack, ...currentIndex].slice(0, MUSIC_MAX_TRACKS)
  const indexBuffer  = Buffer.from(JSON.stringify(updatedIndex, null, 2), 'utf8')
  await sbStorageUpload(supabaseHost, SERVICE_KEY, MUSIC_BUCKET, indexPath, 'application/json', indexBuffer, true)

  console.log(`[FAS:music:upload] ${u} uploaded "${title.trim()}" (${fileBuffer.length} bytes)`)
  return sendJSON(res, 200, { ...newTrack })
}

async function handleMusicDelete(req, res) {
  let creds
  try { creds = getServiceCreds() } catch {
    return sendJSON(res, 503, { error: 'Server credentials not configured.' })
  }

  let rawBody
  try { rawBody = await readBody(req, 4096) } catch {
    return sendJSON(res, 400, { error: 'Bad request.' })
  }
  let body
  try { body = JSON.parse(rawBody.toString('utf8')) } catch {
    return sendJSON(res, 400, { error: 'Invalid JSON body.' })
  }

  const { username, ph, path: storagePath } = body
  if (!username || !ph || !storagePath) return sendJSON(res, 400, { error: 'Missing fields.' })

  const u = username.toLowerCase().replace(/[^a-z0-9_-]/g, '')

  // Verify identity
  const ok = await verifyIdentity(creds.host, creds.key, u, ph)
  if (!ok) return sendJSON(res, 401, { error: 'Authentication failed.' })

  // Security: path must belong to this user's tracks folder (not the index file)
  if (!storagePath.startsWith(u + '/tracks/') || storagePath.endsWith('/_index.json')) {
    return sendJSON(res, 403, { error: 'Cannot delete another member\'s file.' })
  }

  // Delete the audio file from Supabase Storage
  const deleteResult = await sbRequest(creds.host, creds.key, 'DELETE',
    `/storage/v1/object/${MUSIC_BUCKET}`,
    JSON.stringify({ prefixes: [storagePath] })
  )
  if (deleteResult.status !== 200 && deleteResult.status !== 204) {
    console.warn('[FAS:music:delete] Storage delete returned:', deleteResult.status)
  }

  // Update _index.json — remove deleted track entry
  const indexPath = `${u}/tracks/_index.json`
  try {
    const fetchRes = await sbRequest(creds.host, creds.key, 'GET',
      `/storage/v1/object/${MUSIC_BUCKET}/${indexPath}`, null)
    if (fetchRes.status === 200) {
      const idx     = JSON.parse(fetchRes.body.toString('utf8'))
      const updated = idx.filter(t => t.path !== storagePath && t.id !== storagePath)
      const buf     = Buffer.from(JSON.stringify(updated, null, 2), 'utf8')
      await sbStorageUpload(creds.host, creds.key, MUSIC_BUCKET, indexPath, 'application/json', buf, true)
    }
  } catch { /* best-effort */ }

  console.log(`[FAS:music:delete] ${u} deleted "${storagePath}"`)
  return sendJSON(res, 200, { ok: true })
}

/**
 * Shared: extract + validate Supabase service credentials.
 * Returns { host, key } or throws.
 */
function getServiceCreds() {
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY
  const url = process.env.SUPABASE_URL
  if (!key || !url) throw new Error('SUPABASE_SERVICE_ROLE_KEY / SUPABASE_URL not set')
  return { host: new URL(url).hostname, key }
}

/**
 * Verify identity: returns true if username + ph match member_accounts.
 * Uses SELECT on member_accounts with service_role key.
 */
async function verifyIdentity(host, key, username, ph) {
  if (!username || !ph) return false
  const u = username.toLowerCase().replace(/[^a-z0-9_-]/g, '')
  if (!u) return false
  const filter = `username=eq.${encodeURIComponent(u)}&password_hash=eq.${encodeURIComponent(ph)}&select=username`
  const result = await sbRequest(host, key, 'GET', `/rest/v1/member_accounts?${filter}`, null)
  if (result.status !== 200) return false
  try {
    const rows = JSON.parse(result.body.toString())
    return Array.isArray(rows) && rows.length > 0
  } catch {
    return false
  }
}

/**
 * GET /api/dm/threads?username=X
 * Authorization: Bearer <ph>
 * Returns all conversation threads for the authenticated user.
 */
async function handleDMThreads(req, res) {
  let creds
  try { creds = getServiceCreds() } catch (e) {
    return sendJSON(res, 503, { error: 'DM service unavailable.' })
  }

  const qs = new URL(req.url, `http://localhost`).searchParams
  const username = (qs.get('username') || '').toLowerCase().replace(/[^a-z0-9_-]/g, '')
  // ph MUST come from the Authorization header (never the URL)
  const authHeader = req.headers['authorization'] || ''
  const ph = authHeader.startsWith('Bearer ') ? authHeader.slice(7).trim() : ''

  if (!username || !ph) return sendJSON(res, 400, { error: 'Missing username or auth token.' })

  const ok = await verifyIdentity(creds.host, creds.key, username, ph)
  if (!ok) return sendJSON(res, 401, { error: 'Authentication failed.' })

  const filter = `or=(sender.eq.${encodeURIComponent(username)},recipient.eq.${encodeURIComponent(username)})`
    + `&select=sender,recipient,message,file_name,created_at,read_at`
    + `&order=created_at.desc`
  const result = await sbRequest(creds.host, creds.key, 'GET', `/rest/v1/dm_messages?${filter}`, null)
  if (result.status !== 200) return sendJSON(res, 500, { error: 'Could not load threads.' })

  let rows
  try { rows = JSON.parse(result.body.toString()) } catch { rows = [] }

  // Deduplicate into thread summaries
  const seen = {}
  ;(rows || []).forEach(row => {
    const partner = row.sender === username ? row.recipient : row.sender
    const preview = row.file_name ? `📎 ${row.file_name}` : row.message
    if (!seen[partner]) {
      seen[partner] = { username: partner, last_message: preview, last_ts: row.created_at,
        unread: row.recipient === username && !row.read_at ? 1 : 0 }
    } else if (row.recipient === username && !row.read_at) {
      seen[partner].unread++
    }
  })
  const threads = Object.values(seen).sort((a, b) => new Date(b.last_ts) - new Date(a.last_ts))
  sendJSON(res, 200, { threads })
}

/**
 * GET /api/dm/messages?me=X&other=Y
 * Authorization: Bearer <ph>
 * Returns message history between two users.
 */
async function handleDMMessages(req, res) {
  let creds
  try { creds = getServiceCreds() } catch (e) {
    return sendJSON(res, 503, { error: 'DM service unavailable.' })
  }

  const qs    = new URL(req.url, `http://localhost`).searchParams
  const me    = (qs.get('me')    || '').toLowerCase().replace(/[^a-z0-9_-]/g, '')
  const other = (qs.get('other') || '').toLowerCase().replace(/[^a-z0-9_-]/g, '')
  // ph MUST come from the Authorization header (never the URL)
  const authHeader2 = req.headers['authorization'] || ''
  const ph = authHeader2.startsWith('Bearer ') ? authHeader2.slice(7).trim() : ''

  if (!me || !other || !ph) return sendJSON(res, 400, { error: 'Missing me, other, or auth token.' })

  const ok = await verifyIdentity(creds.host, creds.key, me, ph)
  if (!ok) return sendJSON(res, 401, { error: 'Authentication failed.' })

  const filter = `or=(and(sender.eq.${encodeURIComponent(me)},recipient.eq.${encodeURIComponent(other)}),and(sender.eq.${encodeURIComponent(other)},recipient.eq.${encodeURIComponent(me)}))`
    + `&order=created_at.asc&limit=100`
  const result = await sbRequest(creds.host, creds.key, 'GET', `/rest/v1/dm_messages?${filter}`, null)
  if (result.status !== 200) return sendJSON(res, 500, { error: 'Could not load messages.' })

  let rows
  try { rows = JSON.parse(result.body.toString()) } catch { rows = [] }
  sendJSON(res, 200, { messages: rows || [] })
}

/**
 * POST /api/dm/send  { username, ph, recipient, message }
 * Send a text DM. Validates identity then inserts via service_role.
 */
async function handleDMSend(req, res) {
  let creds
  try { creds = getServiceCreds() } catch (e) {
    return sendJSON(res, 503, { error: 'DM service unavailable.' })
  }

  let body
  try {
    const raw = await readBody(req, 64 * 1024)
    body = JSON.parse(raw.toString('utf8'))
  } catch {
    return sendJSON(res, 400, { error: 'Invalid request body.' })
  }

  const { username, ph, recipient, message, file_url, file_type, file_name, file_size_bytes } = body
  if (!username || !ph || !recipient || !message) return sendJSON(res, 400, { error: 'Missing fields.' })

  const sender = username.toLowerCase().replace(/[^a-z0-9_-]/g, '')
  const recip  = recipient.toLowerCase().replace(/[^a-z0-9_-]/g, '')
  const text   = (message || '').trim()
  if (!text || text.length > 500) return sendJSON(res, 400, { error: 'Message must be 1–500 characters.' })

  const ok = await verifyIdentity(creds.host, creds.key, sender, ph)
  if (!ok) return sendJSON(res, 401, { error: 'Authentication failed.' })

  const insertRow = { sender, recipient: recip, message: text }
  if (file_url)       insertRow.file_url        = file_url
  if (file_type)      insertRow.file_type       = file_type
  if (file_name)      insertRow.file_name       = file_name
  if (file_size_bytes) insertRow.file_size_bytes = file_size_bytes
  const payload = JSON.stringify(insertRow)
  const result  = await sbRequest(creds.host, creds.key, 'POST', '/rest/v1/dm_messages', payload)
  if (result.status < 200 || result.status >= 300) {
    console.warn('[FAS:dm:send] Insert error', result.status, result.body.toString())
    return sendJSON(res, 500, { error: 'Failed to send message.' })
  }

  let savedRow = null
  try { const arr = JSON.parse(result.body.toString()); savedRow = Array.isArray(arr) ? arr[0] : arr } catch {}
  sendJSON(res, 200, { message: savedRow })
}

/**
 * POST /api/dm/mark-read  { username, ph, other }
 * Mark all messages from `other` to `username` as read.
 */
async function handleDMMarkRead(req, res) {
  let creds
  try { creds = getServiceCreds() } catch (e) {
    return sendJSON(res, 503, { error: 'DM service unavailable.' })
  }

  let body
  try {
    const raw = await readBody(req, 8 * 1024)
    body = JSON.parse(raw.toString('utf8'))
  } catch {
    return sendJSON(res, 400, { error: 'Invalid request body.' })
  }

  const { username, ph, other } = body
  if (!username || !ph || !other) return sendJSON(res, 400, { error: 'Missing fields.' })

  const me   = username.toLowerCase().replace(/[^a-z0-9_-]/g, '')
  const them = other.toLowerCase().replace(/[^a-z0-9_-]/g, '')

  const ok = await verifyIdentity(creds.host, creds.key, me, ph)
  if (!ok) return sendJSON(res, 401, { error: 'Authentication failed.' })

  // PATCH dm_messages where recipient=me, sender=them, read_at IS NULL
  const filter  = `recipient=eq.${encodeURIComponent(me)}&sender=eq.${encodeURIComponent(them)}&read_at=is.null`
  const payload = JSON.stringify({ read_at: new Date().toISOString() })
  const result  = await sbRequest(creds.host, creds.key, 'PATCH', `/rest/v1/dm_messages?${filter}`, payload)
  if (result.status < 200 || result.status >= 300) {
    return sendJSON(res, 500, { error: 'Failed to mark messages read.' })
  }
  sendJSON(res, 200, { ok: true })
}

server.listen(PORT, '0.0.0.0', () => {
  console.log(`[FAS] Studio running → http://localhost:${PORT}`)
})

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    console.warn(`[FAS] Port ${PORT} is in use — finding and killing the holder...`)
    const killed = killPortHolder(PORT)
    if (killed) {
      console.log(`[FAS] Killed PID ${killed} holding port ${PORT}. Retrying in 1s...`)
      setTimeout(() => {
        server.listen(PORT, '0.0.0.0', () => {
          console.log(`[FAS] Studio running → http://localhost:${PORT}`)
        })
      }, 1000)
    } else {
      console.error(`[FAS] Could not find the process holding port ${PORT}. Restart the workflow manually to clear it.`)
      process.exit(1)
    }
  } else {
    console.error('[FAS] Server error:', err.message)
    process.exit(1)
  }
})

/**
 * Find and kill the process holding a TCP port using /proc/net/tcp.
 * Works on any Linux system (Replit, Docker, etc.) without external tools.
 * Returns the PID that was killed, or null if not found.
 */
function killPortHolder(port) {
  try {
    const hexPort = port.toString(16).toUpperCase().padStart(4, '0')

    // Check both IPv4 and IPv6 tcp tables
    let inode = null
    const tcpFiles = ['/proc/net/tcp', '/proc/net/tcp6']
    for (const tcpFile of tcpFiles) {
      try {
        const lines = fs.readFileSync(tcpFile, 'utf8').trim().split('\n').slice(1)
        for (const line of lines) {
          const parts = line.trim().split(/\s+/)
          const local = parts[1]
          if (!local) continue
          const [, portHex] = local.split(':')
          if (portHex && portHex.toUpperCase() === hexPort) {
            inode = parts[9]
            break
          }
        }
      } catch(ignore) {}
      if (inode) break
    }
    if (!inode) return null

    // Walk /proc/<pid>/fd to find which process owns this inode
    const procDirs = fs.readdirSync('/proc').filter(d => /^\d+$/.test(d))
    for (const pid of procDirs) {
      if (pid === String(process.pid)) continue
      try {
        const fds = fs.readdirSync(`/proc/${pid}/fd`)
        for (const fd of fds) {
          try {
            const link = fs.readlinkSync(`/proc/${pid}/fd/${fd}`)
            if (link.includes(`socket:[${inode}]`)) {
              process.kill(parseInt(pid), 'SIGKILL')
              return pid
            }
          } catch(ignore) {}
        }
      } catch(ignore) {}
    }
    return null
  } catch (e) {
    console.warn('[FAS] killPortHolder error:', e.message)
    return null
  }
}
