const modal=document.querySelector('#modal');const content=document.querySelector('#formContent');
const forms={
 send:{title:'Post a demo request',fields:`<label>Pickup area<input required placeholder="Warwick, RI"></label><label>Drop-off area<input required placeholder="Providence, RI"></label><label>Item category<select><option>Documents</option><option>Clothing</option><option>Small electronics</option><option>Retail pickup/return</option><option>Other ordinary item</option></select></label><label>Approx. weight<input type="number" min="0" max="50" placeholder="10 lb"></label><label class="full">What is being moved?<textarea required placeholder="Describe the item accurately"></textarea></label>`},
 runner:{title:'Post a demo route',fields:`<label>Starting area<input required placeholder="Warwick, RI"></label><label>Destination<input required placeholder="Providence, RI"></label><label>Departure<input type="datetime-local" required></label><label>Maximum detour<select><option>5 minutes</option><option>10 minutes</option><option>15 minutes</option></select></label><label>Vehicle<select><option>Car</option><option>SUV</option><option>Minivan</option></select></label><label>Frequency<select><option>One time</option><option>Weekdays</option><option>Weekly</option></select></label>`},
 business:{title:'Business launch waitlist',fields:`<label>Business name<input required></label><label>Business type<input placeholder="Repair shop, reseller, boutique..."></label><label>Market area<input required placeholder="City, state"></label><label>Weekly requests<input type="number" min="1"></label><label class="full">What do you need moved?<textarea></textarea></label>`}
};
function openForm(type){const f=forms[type];content.innerHTML=`<h2>${f.title}</h2><p>This prototype saves a local demo record only. It does not create a real delivery.</p><div class="form-grid">${f.fields}<div class="full notice">Demo boundary: local, ordinary small items only. No interstate jobs, passengers, weapons, controlled goods, hazardous items, cash, or household moves.</div></div><button class="primary submit" type="submit">Save demo</button>`;modal.dataset.type=type;modal.showModal()}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openForm(b.dataset.open)));
document.querySelector('#demoForm').addEventListener('submit',e=>{e.preventDefault();const records=JSON.parse(localStorage.getItem('routedrop-demo')||'[]');records.push({type:modal.dataset.type,createdAt:new Date().toISOString()});localStorage.setItem('routedrop-demo',JSON.stringify(records));content.innerHTML=`<div class="saved"><strong>Demo saved.</strong><p>Codex/OpenCode should replace this localStorage action with authenticated Supabase writes after implementing jurisdiction gates and RLS.</p><button class="primary" type="button" onclick="document.querySelector('#modal').close()">Done</button></div>`});
