#!/usr/bin/env node
'use strict'

/**
 * ============================================================
 *  FACELESS ANIMAL STUDIOS — ENV CONFIG GENERATOR
 *  scripts/generate-env.js
 *
 *  Writes assets/js/env.js from SUPABASE_URL and SUPABASE_ANON_KEY
 *  environment variables. Exits after writing — does not start a server.
 *
 *  USE CASES:
 *    1. Cloudflare Pages build step:
 *         Build command: node scripts/generate-env.js
 *         Set SUPABASE_URL and SUPABASE_ANON_KEY in CF Pages dashboard
 *
 *    2. Manual regeneration during development:
 *         node scripts/generate-env.js
 *
 *    Note: server.js runs this automatically on startup.
 *    You only need this script for build pipelines without the server.
 * ============================================================
 */

const fs   = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')

const url  = process.env.SUPABASE_URL      || ''
const key  = process.env.SUPABASE_ANON_KEY || ''
const ready = Boolean(url && key)

const content = [
  '/* AUTO-GENERATED by scripts/generate-env.js — do not edit manually.',
  '   Set SUPABASE_URL and SUPABASE_ANON_KEY env vars and re-run this script.',
  '   This file is gitignored. The build process regenerates it on every deploy. */',
  '',
  'window.__FAS_CONFIG = {',
  `  supabaseUrl:     ${JSON.stringify(url)},`,
  `  supabaseAnonKey: ${JSON.stringify(key)},`,
  `  ready:           ${JSON.stringify(ready)},`,
  '}',
].join('\n')

const outPath = path.join(ROOT, 'assets', 'js', 'env.js')

try {
  fs.writeFileSync(outPath, content, 'utf8')
  console.log('[FAS] Wrote assets/js/env.js')
  if (ready) {
    console.log('[FAS] Supabase configured — URL and key present.')
  } else {
    console.warn('[FAS] WARNING: SUPABASE_URL or SUPABASE_ANON_KEY is not set.')
    console.warn('[FAS]   env.js written with empty values — Supabase will not activate.')
  }
} catch (e) {
  console.error('[FAS] Failed to write assets/js/env.js:', e.message)
  process.exit(1)
}
