"use strict";
const http=require("node:http"),crypto=require("node:crypto"),dns=require("node:dns").promises,net=require("node:net");
const{chromium}=require("playwright");
const NAME="Faceless Operator — Browser Action Engine",VERSION="1.0.0";
const int=(n,d,min,max)=>{const v=Number(process.env[n]||d);if(!Number.isInteger(v)||v<min||v>max)throw Error(n+" invalid");return v};
const PORT=int("PORT",8788,1,65535),TTL=int("SESSION_TTL_MS",1800000,60000,86400000),MAX=int("MAX_CONCURRENT_SESSIONS",5,1,25),RATE=int("RATE_LIMIT_MAX",90,1,10000),WINDOW=int("RATE_LIMIT_WINDOW_MS",60000,1000,3600000),NAV=int("NAVIGATION_TIMEOUT_MS",30000,1000,120000),ACT=int("ACTION_TIMEOUT_MS",15000,500,60000);
const keys=String(process.env.FACELESS_OPERATOR_API_KEYS||process.env.FACELESS_OPERATOR_API_KEY||"").split(",").map(x=>x.trim()).filter(Boolean);
if(!keys.length&&process.env.NODE_ENV==="production")throw Error("FACELESS_OPERATOR_API_KEY required");
const origins=new Set(String(process.env.CORS_ALLOWED_ORIGINS||"https://chatgpt.com").split(",").map(x=>x.trim()).filter(Boolean));
const sessions=new Map(),rates=new Map(),approvals=new Map();
class OpError extends Error{constructor(code,message,status=400,details){super(message);Object.assign(this,{code,status,details})}}
const str=(v,n,max=4096,required=true)=>{if((!required&&v===undefined)||(typeof v==="string"&&v.length<=max&&(!required||v.length)))return v;throw new OpError("VALIDATION_ERROR",`${n} must be ${required?"a non-empty":"an optional"} string no longer than ${max} characters`)};
const rid=req=>typeof req.headers["x-request-id"]==="string"&&/^[\w.-]{1,80}$/.test(req.headers["x-request-id"])?req.headers["x-request-id"]:crypto.randomUUID();
const headers=req=>{const h={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"},o=req.headers.origin;if(o&&origins.has(o))Object.assign(h,{"access-control-allow-origin":o,vary:"Origin","access-control-allow-headers":"authorization,content-type,x-request-id,x-faceless-approval","access-control-allow-methods":"GET,POST,DELETE,OPTIONS","access-control-max-age":"600"});return h};
const send=(req,res,status,data)=>{res.writeHead(status,headers(req));res.end(JSON.stringify(data))};
const fail=(req,res,e,id)=>{const x=e instanceof OpError?e:new OpError("INTERNAL_ERROR","Operator request failed",500);if(!(e instanceof OpError))console.error(JSON.stringify({level:"error",requestId:id,message:e?.message}));send(req,res,x.status,{ok:false,error:{code:x.code,message:x.message,...(x.details?{details:x.details}:{})},requestId:id})};
async function body(req){let n=0,a=[];for await(const c of req){n+=c.length;if(n>262144)throw new OpError("BODY_TOO_LARGE","Request body is too large",413);a.push(c)}if(!a.length)return{};try{return JSON.parse(Buffer.concat(a))}catch{throw new OpError("INVALID_JSON","Request body must be valid JSON")}}
const equal=(a,b)=>{a=Buffer.from(String(a));b=Buffer.from(String(b));return a.length===b.length&&crypto.timingSafeEqual(a,b)};
function auth(req){const token=/^Bearer\s+(.+)$/i.exec(String(req.headers.authorization||""))?.[1]||"",key=keys.find(k=>equal(k,token));if(!key)throw new OpError("UNAUTHORIZED","Valid bearer authentication is required",401);return crypto.createHash("sha256").update(key).digest("hex").slice(0,24)}
function limit(owner){const now=Date.now(),b=rates.get(owner);if(!b||now>=b.resetAt)return rates.set(owner,{count:1,resetAt:now+WINDOW});if(++b.count>RATE)throw new OpError("RATE_LIMITED","Too many requests",429,{retryAfterMs:b.resetAt-now})}
const norm=x=>x.startsWith("::ffff:")?x.slice(7):x.split("%")[0];
function blocked(raw){const x=norm(raw).toLowerCase();if(net.isIPv4(x)){const[a,b]=x.split(".").map(Number);return a===0||a===10||a===127||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&(b===0||b===168))||(a===198&&(b===18||b===19))||a>=224}if(net.isIPv6(x))return x==="::"||x==="::1"||x.startsWith("fc")||x.startsWith("fd")||/^fe[89ab]/.test(x)||x.startsWith("2001:db8:")||x.startsWith("2001:10:")||x.startsWith("64:ff9b:1:");return true}
async function safeUrl(value){let u;try{u=new URL(str(value,"url",8192))}catch(e){if(e instanceof OpError)throw e;throw new OpError("INVALID_URL","url must be an absolute HTTP or HTTPS URL")}if(!["http:","https:"].includes(u.protocol)||u.username||u.password)throw new OpError("UNSAFE_URL","Only credential-free HTTP and HTTPS URLs are allowed");const host=u.hostname.toLowerCase().replace(/\.$/,"").replace(/^\[|\]$/g,"");if(!host||host==="localhost"||host.endsWith(".localhost")||host.endsWith(".local")||host==="metadata.google.internal"||host==="instance-data.ec2.internal")throw new OpError("SSRF_BLOCKED","Local, private, and metadata destinations are blocked",403);let addresses;if(net.isIP(host))addresses=[{address:host}];else try{addresses=await dns.lookup(host,{all:true,verbatim:true})}catch{throw new OpError("DNS_FAILED","Destination hostname could not be resolved")};if(!addresses.length||addresses.some(x=>blocked(x.address)))throw new OpError("SSRF_BLOCKED","Destination resolved to a blocked network",403);return u.toString()}
async function close(s){sessions.delete(s.id);for(const[id,a]of approvals)if(a.sessionId===s.id)approvals.delete(id);try{await s.context.close()}catch{}try{await s.browser.close()}catch{}}
async function create(owner){if(sessions.size>=MAX)throw new OpError("SESSION_CAPACITY","Maximum concurrent browser sessions reached",503);const browser=await chromium.launch({headless:true,args:["--disable-dev-shm-usage","--no-first-run","--disable-background-networking"]}),context=await browser.newContext({viewport:{width:1365,height:900},acceptDownloads:false,serviceWorkers:"block"});await context.route("**/*",async r=>{try{await safeUrl(r.request().url());await r.continue()}catch{await r.abort("blockedbyclient")}});const page=await context.newPage();page.setDefaultNavigationTimeout(NAV);page.setDefaultTimeout(ACT);const id=crypto.randomUUID(),s={id,owner,browser,context,page,lastAt:Date.now()};sessions.set(id,s);return{id,expiresInMs:TTL}}
function get(id,owner){if(!/^[0-9a-f-]{36}$/i.test(String(id)))throw new OpError("INVALID_SESSION","Invalid session ID");const s=sessions.get(id);if(!s)throw new OpError("SESSION_NOT_FOUND","Session not found or expired",404);if(s.owner!==owner)throw new OpError("SESSION_FORBIDDEN","Session belongs to another authenticated owner",403);if(Date.now()-s.lastAt>TTL){void close(s);throw new OpError("SESSION_EXPIRED","Session has expired",410)}s.lastAt=Date.now();return s}
const risky=/\b(buy|purchase|checkout|pay|place order|submit order|delete|remove account|publish|post|send|message|email|transfer|withdraw|change password|security|2fa|two-factor|confirm)\b/i;
const fp=a=>crypto.createHash("sha256").update(JSON.stringify({action:a.action,selector:a.selector||"",url:a.url||"",text:a.action==="type"?"[redacted]":a.text||""})).digest("hex");
const needs=a=>a.consequential===true||risky.test([a.selector,a.label,a.purpose,a.url].filter(Boolean).join(" "));
function approve(s,a){if(!needs(a))return;const t=str(a.approvalToken,"approvalToken",200),x=approvals.get(t);approvals.delete(t);if(!x||x.owner!==s.owner||x.sessionId!==s.id||x.expiresAt<Date.now()||x.fingerprint!==fp(a))throw new OpError("APPROVAL_REQUIRED","This consequential action requires a fresh, matching explicit approval",409)}
async function act(s,a){if(!a||typeof a!=="object"||Array.isArray(a))throw new OpError("VALIDATION_ERROR","Action must be an object");const action=str(a.action,"action",32),p=s.page;approve(s,a);if(action==="open"){const u=await safeUrl(a.url),r=await p.goto(u,{waitUntil:"domcontentloaded",timeout:NAV});await safeUrl(p.url());return{url:p.url(),title:await p.title(),status:r?.status()||null}}if(action==="read")return{url:p.url(),title:await p.title(),text:(await p.locator("body").innerText()).slice(0,50000)};if(action==="click"){const before=p.url();await p.locator(str(a.selector,"selector",2048)).first().click();await p.waitForTimeout(250);if(p.url()!==before)await safeUrl(p.url());return{url:p.url(),title:await p.title()}}if(action==="type"){const text=str(a.text??"","text",20000,false)??"";await p.locator(str(a.selector,"selector",2048)).first().fill(text);return{ok:true,charactersEntered:text.length}}if(action==="wait"){const ms=Math.min(Math.max(Number(a.ms)||500,0),10000);await p.waitForTimeout(ms);return{ok:true,waitedMs:ms}}if(action==="back"||action==="forward"){await(action==="back"?p.goBack({waitUntil:"domcontentloaded"}):p.goForward({waitUntil:"domcontentloaded"}));if(p.url()!=="about:blank")await safeUrl(p.url());return{url:p.url(),title:await p.title()}}if(action==="screenshot"){const b=await p.screenshot({fullPage:Boolean(a.fullPage)});return{mimeType:"image/png",base64:b.toString("base64")}}throw new OpError("UNSUPPORTED_ACTION","Unsupported browser action")}
const props={sessionId:{type:"string",format:"uuid"},selector:{type:"string",maxLength:2048},url:{type:"string",maxLength:8192},text:{type:"string",maxLength:20000},ms:{type:"integer",minimum:0,maximum:10000},fullPage:{type:"boolean"},purpose:{type:"string",maxLength:500},consequential:{type:"boolean"},approvalToken:{type:"string",maxLength:200}},schema=(required=["sessionId"])=>({type:"object",additionalProperties:false,required,properties:props});
const tools=[
 {name:"browser_session_create",title:"Create browser session",description:"Create an isolated browser session owned by the authenticated caller.",inputSchema:schema([]),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true}},
 {name:"browser_open",title:"Open webpage",description:"Open a public HTTP(S) webpage. Private and internal networks are blocked.",inputSchema:schema(["sessionId","url"]),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},
 {name:"browser_read",title:"Read webpage",description:"Read visible page text, title, and URL.",inputSchema:schema(),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}},
 {name:"browser_click",title:"Click webpage element",description:"Click a selector. Consequential clicks require a one-time explicit approval token.",inputSchema:schema(["sessionId","selector"]),annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true}},
 {name:"browser_type",title:"Type into webpage",description:"Fill a form field. Typed text is never logged. Consequential actions require approval.",inputSchema:schema(["sessionId","selector","text"]),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true}},
 ...["wait","back","forward","screenshot"].map(n=>({name:"browser_"+n,title:"Browser "+n,description:`${n} in the current browser session.`,inputSchema:schema(n==="wait"?["sessionId","ms"]:["sessionId"]),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true}})),
 {name:"browser_action_approve",title:"Approve consequential action",description:"Only after explicit user confirmation, issue a matching one-time approval token valid for 60 seconds.",inputSchema:{...schema(["sessionId","action","confirmation"]),properties:{...props,action:{type:"string",enum:["click","type"]},confirmation:{type:"boolean",const:true}}},annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:false}},
 {name:"browser_session_close",title:"Close browser session",description:"Close and delete a browser session.",inputSchema:schema(),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}}
];
async function call(owner,name,args){if(name==="browser_session_create")return create(owner);const s=get(args?.sessionId,owner);if(name==="browser_session_close"){await close(s);return{ok:true}}if(name==="browser_action_approve"){if(args.confirmation!==true)throw new OpError("APPROVAL_REQUIRED","Explicit confirmation is required",409);const a={...args,consequential:true},token=crypto.randomBytes(32).toString("base64url");approvals.set(token,{owner,sessionId:s.id,fingerprint:fp(a),expiresAt:Date.now()+60000});return{approvalToken:token,expiresInMs:60000}}const map={browser_open:"open",browser_read:"read",browser_click:"click",browser_type:"type",browser_wait:"wait",browser_back:"back",browser_forward:"forward",browser_screenshot:"screenshot"};if(!map[name])throw new OpError("TOOL_NOT_FOUND","Unknown MCP tool",404);return act(s,{...args,action:map[name]})}
async function mcp(req,res,owner,p){const reply=(result,error)=>send(req,res,200,{jsonrpc:"2.0",id:p.id??null,...(error?{error}:{result})});if(!p||p.jsonrpc!=="2.0"||typeof p.method!=="string")return reply(null,{code:-32600,message:"Invalid Request"});if(p.method==="initialize")return reply({protocolVersion:"2025-06-18",capabilities:{tools:{listChanged:false}},serverInfo:{name:NAME,version:VERSION},instructions:"Operate public websites only. Never bypass CAPTCHA, 2FA, anti-bot controls, or site security. Obtain explicit user approval before consequential actions."});if(p.method==="notifications/initialized"){res.writeHead(202,headers(req));return res.end()}if(p.method==="tools/list")return reply({tools});if(p.method==="tools/call")try{const data=await call(owner,p.params?.name,p.params?.arguments||{});return reply({structuredContent:data,content:[{type:"text",text:JSON.stringify(data)}],isError:false})}catch(e){const x=e instanceof OpError?e:new OpError("TOOL_ERROR","Browser operation failed",500);return reply({structuredContent:{ok:false,error:{code:x.code,message:x.message}},content:[{type:"text",text:`${x.code}: ${x.message}`}],isError:true})}return reply(null,{code:-32601,message:"Method not found"})}
const server=http.createServer(async(req,res)=>{const id=rid(req),start=Date.now();try{const u=new URL(req.url,"http://operator.invalid");if(req.method==="OPTIONS"){if(req.headers.origin&&!origins.has(req.headers.origin))throw new OpError("CORS_DENIED","Origin is not allowed",403);res.writeHead(204,headers(req));return res.end()}if(u.pathname==="/health"&&req.method==="GET")return send(req,res,200,{ok:true,name:NAME,version:VERSION,aiModel:false,sessions:sessions.size});const owner=auth(req);limit(owner);if(u.pathname==="/mcp"&&req.method==="POST")return mcp(req,res,owner,await body(req));if(u.pathname==="/v1/sessions"&&req.method==="POST")return send(req,res,201,{ok:true,session:await create(owner),requestId:id});const m=/^\/v1\/sessions\/([0-9a-f-]{36})(?:\/(actions|approvals))?$/.exec(u.pathname);if(!m)throw new OpError("NOT_FOUND","Route not found",404);const s=get(m[1],owner);if(req.method==="DELETE"&&!m[2]){await close(s);return send(req,res,200,{ok:true,requestId:id})}if(req.method==="POST"&&m[2]==="actions")return send(req,res,200,{ok:true,sessionId:s.id,result:await act(s,await body(req)),requestId:id});if(req.method==="POST"&&m[2]==="approvals"){const a=await body(req);if(req.headers["x-faceless-approval"]!=="confirmed")throw new OpError("APPROVAL_REQUIRED","Explicit approval header is required",409);const token=crypto.randomBytes(32).toString("base64url");approvals.set(token,{owner,sessionId:s.id,fingerprint:fp(a),expiresAt:Date.now()+60000});return send(req,res,201,{ok:true,approvalToken:token,expiresInMs:60000,requestId:id})}throw new OpError("METHOD_NOT_ALLOWED","Method not allowed",405)}catch(e){fail(req,res,e,id)}finally{console.log(JSON.stringify({level:"info",requestId:id,method:req.method,path:String(req.url||"").split("?")[0],status:res.statusCode,durationMs:Date.now()-start}))}});
const sweep=setInterval(async()=>{const now=Date.now();for(const s of sessions.values())if(now-s.lastAt>TTL)await close(s);for(const[id,a]of approvals)if(a.expiresAt<now)approvals.delete(id);for(const[o,b]of rates)if(b.resetAt<now)rates.delete(o)},30000);sweep.unref();
async function shutdown(){clearInterval(sweep);await Promise.all([...sessions.values()].map(close));server.close(()=>process.exit(0));setTimeout(()=>process.exit(1),10000).unref()}process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);
if(require.main===module)server.listen(PORT,"0.0.0.0",()=>console.log(JSON.stringify({level:"info",event:"listening",name:NAME,version:VERSION,port:PORT})));
module.exports={server,safeUrl,blocked};
